# Nombre del Workflow
name: Generar y Desplegar Sitio desde Google Sheets

# Disparadores (Triggers)
on:
  # 1. Permite ejecutar este workflow manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:

  # 2. Opcional: Ejecutar el workflow en un horario programado
  # schedule:
  #   # Ejecutar todos los días a las 02:00 AM UTC
  #   - cron: '0 2 * * *'

  # 3. Opcional: Ejecutar si hay cambios en el script o las plantillas
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'builder.py'
  #     - 'templates/**'
  #     - '.github/workflows/publish.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 3: Instalar las dependencias de Python
      - name: Instalar dependencias desde requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar el script generador
      - name: Ejecutar builder.py para generar archivos HTML
        env:
          # El secreto se pasa como una variable de entorno al script
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python builder.py

      # Paso 5: Hacer commit y push de los cambios al repositorio (si los hay)
      - name: Commit y Push de los archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensaje del commit
          commit_message: 'build(automation): Regenerar sitio desde Google Sheets'
          # Rama a la que hacer push
          branch: main
          # Patrón de archivos a incluir en el commit
          file_pattern: 'publicaciones.html publicaciones/*'