# Workflow de CI/CD para el Proyecto Runa v3.0 (IaC + Supabase)

name: Orquestador de Runa (Infraestructura y Contenido)

on:
  # Disparador manual que permite elegir qué job ejecutar
  workflow_dispatch:

  # Ejecución programada solo para el job de publicación de contenido
  schedule:
    - cron: '0 * * * *' # Cada hora

jobs:
  # --- JOB 1: CONSTRUCCIÓN DE INFRAESTRUCTURA ---
  build_infra:
    name: 🏗️ Construir/Actualizar Infraestructura de BD
    # Este job solo se ejecuta si el trigger fue manual
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Orquestador de Infraestructura
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: python infra_builder.py

  # --- JOB 2: PUBLICACIÓN DE CONTENIDO ---
  publish_content:
    name: 🚀 Publicar Nuevo Contenido
    runs-on: ubuntu-latest
    # Este job necesita que el de infra termine si ambos se ejecutan, 
    # pero se ejecutará siempre, incluso si 'build_infra' se salta (por ser un schedule)
    needs: build_infra
    if: always()

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Publicador de Contenido
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python builder.py

      - name: Commit y Push de los archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'build(content): Regenerar sitio con nuevos artículos'
          branch: main
          file_pattern: 'publicaciones.html publicaciones/*'
          # Añadir el log al commit para poder depurar
          add: 'runa_automation.log'